#!/usr/bin/env bash

# @file Simple-minded script to display shows from this date (in other years)
#       and/or optionally add them to the current play list and start playing.
#       Call as `deadoftheday` to limit search to The_Grateful_Dead.
# @todo Better argument handling
# @todo Accumulate and display total length of shows
# @see  For arguments help, try: `showoftheday help`

NAME=`basename $0`
DATE=$1
PLAY=$2

if [ "$DATE" == '-h' ] || [ "$DATE" == 'help' ]; then
    echo "With no args,          display shows from today's date (in other years)."
    echo "With arg 'mm-dd',      display shows played on that date"
    echo "With last arg 'play',  append shows from the given date to rhythmbox."
    exit
fi

QUEUE=0
if [ "x$DATE" == "x" ] || [ "$DATE" == "play" ]; then
    if [ "$DATE" == "play" ]; then
        QUEUE=1
    fi
    DATE=`date +"%m-%d"`
fi
if [ "$PLAY" == "play" ]; then
    QUEUE=1
fi

if [ $NAME = "deadoftheday" ]; then
    PREFIX='The_Grateful_Dead/'
else
    PREFIX=''
fi

DATABASE="mariadb"
assert_database() {
    [ "$( systemctl is-active ${DATABASE} )" == "inactive" ] && sudo systemctl start ${DATABASE}
}

MOUNTDIR=${MOUNTDIR-/cycles/flac}
assert_mountdir() {
  [ $( mountpoint ${MOUNTDIR} > /dev/null ) ] || mount ${MOUNTDIR}
}

assert_database
#assert_mountdir


FILES=$(mysql music -B -N -e "SELECT filepath FROM songs WHERE filepath LIKE '%/${PREFIX}____-${DATE}%' ORDER BY filepath ASC")

COUNT=0
ADDING=''
if [ "$QUEUE" == "1" ]; then
    rhythmbox-client --clear-queue
fi
LASTDIR=''

for i in $FILES; do
    THISDIR="$( dirname $i )"
    SHORT="${THISDIR:13}"
    if [ "$THISDIR" != "$LASTDIR" ]; then
	    LASTDIR=$THISDIR
	    echo "${ADDING}${SHORT}"
	    (( COUNT++ ))
    fi
    if [ "$QUEUE" == "1" ]; then
	rhythmbox-client --enqueue $i
    fi
done

echo ""
echo "$COUNT concerts played on this day in history ($DATE)!"

if [ "$QUEUE" == "1" ]; then
    rhythmbox-client --play
fi
